'use strict';
function updateNotice(){const missing=[];if(state.errors.observed)missing.push('live gauge');if(state.errors.predicted)missing.push('astronomical tide');if(state.errors.model)missing.push('model forecast');if(state.errors.alerts)missing.push('NWS alerts');if(state.errors.weatherObservation)missing.push('nearby measured weather');if(state.errors.weatherForecast)missing.push('coastal-point weather forecast');const recent=state.obs.at(-1);const stale=recent&&now()-recent.t>45*60000;const node=$('notice');if(!missing.length&&!stale){node.classList.add('hidden');return;}node.classList.remove('hidden');const lines=[];if(missing.length)lines.push('Some live feeds are unavailable: '+missing.join(', ')+'. A dash means no data, not zero risk.');if(stale)lines.push('The most recent gauge reading is '+relative(recent.t)+'; treat it as stale.');lines.push('Open the official NOAA/NWS links below for current conditions.');$('noticeText').textContent=lines.join(' ');}
function updateClock(){$('currentClock').textContent=fmt(now(),{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'});const o=state.obs.at(-1);const healthy=!!o&&now()-o.t<45*60000;$('liveDot').className='dot '+(healthy?'good':state.loading?'warn':'bad');$('liveText').textContent=state.loading?'Refreshing feeds':healthy?'Gauge current':o?'Gauge delayed':'Live data unavailable';if(state.lastSuccess)$('syncTime').textContent='Last successful data refresh '+relative(state.lastSuccess);}
function render(){renderSummary();renderHistoricalComparison();renderMarine();renderWeather();renderTable();renderCalendar();renderCoastalIntelligence();renderAlerts();renderChart();renderBriefing();updateNotice();updateClock();}
async function load(){
if(state.loading)return;state.loading=true;state.lastAttempt=now();updateClock();const t=now(),start=ymd(t-3*86400000),end=ymd(t+4*86400000);
const calls=[
['observed',query('water_level',{date:'recent'}),data=>{const pts=decodeSeries(data,['data','observations']);if(!pts.length)throw Error('No gauge observations returned');state.obs=pts;},0],
['predicted',query('predictions',{begin_date:start,end_date:end,interval:'6'}),data=>{const pts=decodeSeries(data,['predictions','data']);if(!pts.length)throw Error('No short-range tide predictions returned');state.predShort=pts;combinePredictions();},5*60000],
['longTide',query('predictions',{begin_date:ymd(t),end_date:ymd(t+30*86400000),interval:'15'}),data=>{const pts=decodeSeries(data,['predictions','data']);if(!pts.length)throw Error('No 30-day tide predictions returned');state.predLong=pts;combinePredictions();},6*3600000],
['highs',query('predictions',{begin_date:ymd(t),end_date:ymd(t+30*86400000),interval:'hilo'}),data=>{const pts=decodeHighs(data);if(!pts.length)throw Error('No 30-day high tide predictions returned');state.highs=pts;},6*3600000],
['model',query('ofs_water_level',{begin_date:ymd(t-86400000),end_date:ymd(t+4*86400000)}),data=>{const pts=decodeSeries(data,['data','predictions','ofs_water_level','forecast']);const future=pts.filter(p=>p.t>t-10*60000&&p.t<t+72*3600000);if(!future.length)throw Error('No near-term model guidance returned');state.model=pts.filter(p=>p.t<=t+72*3600000);},0],
['alerts','https://api.weather.gov/alerts/active?point=43.48,-70.38',data=>{if(!Array.isArray(data.features))throw Error('No valid NWS alert response');state.alerts=data.features;},0]
];
for(const [name,url,save,interval] of calls){if(interval&&!shouldFetch(name,interval))continue;try{const data=await getJSON(url);save(data);state.lastFetched[name]=now();delete state.errors[name];if(['observed','predicted','model','alerts'].includes(name))health('health'+name[0].toUpperCase()+name.slice(1),true,name==='alerts'?state.alerts.length+' active':'Connected');state.lastSuccess=now();}catch(err){if(name==='model')state.model=[];state.errors[name]=String(err?.message||err);if(['observed','predicted','model','alerts'].includes(name))health('health'+name[0].toUpperCase()+name.slice(1),false,'Unavailable');console.warn('Saco Coast Watch '+name+':',err);}render();if(name!=='alerts')await new Promise(r=>setTimeout(r,250));}
await Promise.all([loadWeather(),loadMarine(),loadBriefing()]);state.loading=false;$('lastUpdated').textContent='Last checked '+fmt(now(),{hour:'numeric',minute:'2-digit',timeZoneName:'short'})+' · 60-second live checks';render();
}
function exportCSV(){const timestamps=new Set([...state.obs,...state.pred,...state.model].map(x=>x.t));const lines=['utc_time,observed_ft_MLLW,astronomical_tide_ft_MLLW,model_guidance_ft_MLLW'];const obs=new Map(state.obs.map(x=>[x.t,x.v])),pred=new Map(state.pred.map(x=>[x.t,x.v])),model=new Map(state.model.map(x=>[x.t,x.v]));for(const t of [...timestamps].sort((a,b)=>a-b)){lines.push([new Date(t).toISOString(),obs.get(t)??'',pred.get(t)??'',model.get(t)??''].join(','));}const blob=new Blob([lines.join('\n')+'\n'],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='saco-coast-watch-'+ymd(now())+'.csv';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
$('exportBtn').addEventListener('click',exportCSV);
$('briefOpen').addEventListener('click',()=>{const d=$('briefingDialog');if(typeof d.showModal==='function')d.showModal();else d.setAttribute('open','');});
$('briefClose').addEventListener('click',()=>$('briefingDialog').close());
$('briefingDialog').addEventListener('click',e=>{if(e.target===$('briefingDialog'))$('briefingDialog').close();});
$('refreshBtn').addEventListener('click',()=>window.location.reload());
document.querySelectorAll('[data-days]').forEach(btn=>btn.addEventListener('click',()=>{state.days=Number(btn.dataset.days);document.querySelectorAll('[data-days]').forEach(b=>{b.classList.toggle('active',b===btn);b.setAttribute('aria-pressed',String(b===btn));});render();}));
$('showFlood').addEventListener('change',e=>{state.showFlood=e.target.checked;renderChart();});$('showModel').addEventListener('change',e=>{state.showModel=e.target.checked;renderChart();});
setInterval(updateClock,10000);setInterval(()=>{if(!document.hidden)load();},60*1000);
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&(!state.lastAttempt||now()-state.lastAttempt>=60*1000))load();});let chartResizeTimer;window.addEventListener('resize',()=>{clearTimeout(chartResizeTimer);chartResizeTimer=setTimeout(renderChart,120);});load();
